services:
  postgres:
    image: timescale/timescaledb-postgis:latest-pg13
    ports: ['5432:5432']
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sih
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports: ['6379:6379']
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ['9000:9000', '9001:9001']
    volumes:
      - minio:/data
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports: ['2181:2181']
  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    ports: ['9092:9092']
    depends_on: ['zookeeper']
  mosquitto:
    image: eclipse-mosquitto:2
    ports: ['1883:1883']
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --http-port 8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports: ['8080:8080']
volumes:
  pgdata: {}
  minio: {}
